config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :zipcodes
  root 'zipcodes#index'
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
  def self.search(query)
    where("zip like ?", "%#{query}%")
  end
  scope :selected, lambda { where(:spot1 => "t") | where(:spot2 => "t") | where(:spot3 => "t") | where(:spot4 => "t") | where(:spot5 => "t") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @zipcodes = Zipcode.selected
  end
end

app/controllers/zipcodes_controller.rb
class ZipcodesController < ApplicationController
  before_action :set_zipcode, only: [:edit, :update]
  # GET /zipcodes
  # GET /zipcodes.json
  def index
    if params[:search]
      @zipcodes = Zipcode.search(params[:search]).order("created_at DESC")
    else
      @zipcodes = Zipcode.all.order('created_at DESC')
    end
  end

  def edit
  end

  # PATCH/PUT /zipcodes/1
  def update
    respond_to do |format|
      if @zipcode.update(zipcode_params)
        format.html { redirect_to zipcodes_path }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zipcode
      @zipcode = Zipcode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zipcode_params
      params.require(:zipcode).permit(:zip, :spot1, :spot2, :spot3, :spot4, :spot5, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/zipcodes_helper.rb
module ZipcodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/payments/_form.html.erb
<style type="text/css">
#wrapper{
  float:left;
  min-width: 200px;
}
</style>
<div id = "wrapper">
  <div class="row">
    Credit Card<input type="text" class="input" name="creditcard">
  </div>
  <div class ="row">
    Expiration
    <div class = "input">
      <select>
        <option value="1-January">1-January</option>
        <option value="2-February">2-February</option>
        <option value="3-March">3-March</option>
        <option value="4-April">4-April</option>
        <option value="5-May">5-May</option>
        <option value="6-June">6-June</option>
        <option value="7-July">7-July</option>
        <option value="8-August">8-August</option>
        <option value="9-September">9-September</option>
        <option value="10-October">10-October</option>
        <option value="11-November">11-November</option>
        <option value="12-December">12-December</option>
      </select>
    </div>
    <div class = "input">
      <select>
        <option value="2014">2014</option>
        <option value="2015">2015</option>
        <option value="2016">2016</option>
        <option value="2017">2017</option>
        <option value="2018">2018</option>
        <option value="2019">2019</option>
        <option value="2020">2020</option>
        <option value="2021">2021</option>
        <option value="2022">2022</option>
        <option value="2023">2023</option>
      </select>
    </div>
  </div>
  <div class="row">
    Email<input type="text" class="input" name="creditcard">
  </div>
  <div class="row">
    <%= link_to 'Purchase and Launch Ad Campaign', payments_path, :color=> '#FFFFFF', :class=> "button" %>
  </div>
</div>

app/views/payments/_paytable.html.erb
<table>
  <thead>
  <tr>
    <th>Zip</th>
    <th>Total Spots</th>
    <th>Price Per Month</th>
  </tr>
  </thead>
  <tbody>
    <% @totalprice = 0
    @zipcodes.each do |zipcode|
    @ziptotal = 0
    @counter = 0 %>
    <tr>
      <% if zipcode.spot1 %>
        <% @counter += 1 %>
      <% end %>
      <% if zipcode.spot2 %>
        <% @counter += 1 %>
      <% end %>
      <% if zipcode.spot3 %>
        <% @counter += 1 %>
      <% end %>
      <% if zipcode.spot4 %>
        <% @counter += 1 %>
      <% end %>
      <% if zipcode.spot5  %>
        <% @counter += 1 %>
      <% end %>
      <td><%= zipcode.zip %></td>
      <td><%= @counter %> </td>
      <td><div id = "select-zip">$<%@ziptotal = @counter * zipcode.price %><%= @ziptotal %>.00/mo</div></td>
    </tr>
    <% @totalprice += @ziptotal %>
    <% end %>
  </tbody>
</table>

app/views/payments/index.html.erb
<style type="text/css">
#paymentswrapper{
  float:left;
  padding-left: 10px;
}
</style>
<div id = "paymentswrapper">
  <div class="row">
    <h3>Just a few more details</h3>
  </div>
  <div class="row">
    Select Payment Plan
  </div>
  <div class="row">
    <%= link_to 'Annual Recuring Monthly', payments_path, :color=> '#FFFFFF', :class=> "button" %>
    <%= link_to '6 Months Prepaid', payments_path, :color=> '#FFFFFF', :class=> "button" %>
    <%= render "paytable" %>
  </div>
  <h3>Total Charge: $<%= @totalprice %>.00/mo</h3>
  <%= render 'form' %>
</div>

app/views/zipcodes/_form.html.erb
<%= simple_form_for(@zipcode) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <table>
      <tr>
        <td>
          <%= f.input :spot1  %>
          $<%= @zipcode.price  %>
         </td>
         <td>
          <%= f.input :spot2 %>
          $<%= @zipcode.price  %>
         </td>
         <td>
          <%= f.input :spot3 %>
          $<%= @zipcode.price  %>
         </td>
         <td>
          <%= f.input :spot4 %>
          $<%= @zipcode.price  %>
         </td>
         <td>
          <%= f.input :spot5 %>
          $<%= @zipcode.price  %>
         </td>
      </tr>
  </table>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "Get Spots Now" %>
  </div>
<% end %>

app/views/zipcodes/_ziptable.html.erb
<table>
  <thead>
    <tr>
      <th>Zip</th>
      <th>Spot1</th>
      <th>Spot2</th>
      <th>Spot3</th>
      <th>Spot4</th>
      <th>Spot5</th>
      <th>Monthly Ad Displays</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @zipcodes.each do |zipcode| %>
  <% @counter = 0%>
  <tr>
      <td><%= zipcode.zip %></td>
      <td><% if zipcode.spot1 == false %>
      Available
      <% elsif %>
      <% @counter += 1 %>
      $<%=zipcode.price%>
      <% end %></td>
      <td><% if zipcode.spot2 == false %>
      Available
      <% elsif %>
      <% @counter += 1 %>
      $<%=zipcode.price%>
      <% end %></td>
      <td><% if zipcode.spot3 == false %>
      Available
      <% elsif %>
      <% @counter += 1 %>
      $<%=zipcode.price%>
      <% end %></td>
      <td><% if zipcode.spot4 == false %>
      Available
      <% elsif %>
      <% @counter += 1 %>
      $<%=zipcode.price%>
      <% end %></td>
      <td><% if zipcode.spot5 == false %>
      Available
      <% elsif %>
      <% @counter += 1 %>
      $<%=zipcode.price%>
      <% end %></td>
      <td><%=@counter * 5000%></td>
      <td><div id = "select-zip"><%= link_to "Select ZIP Code", edit_zipcode_path(zipcode) %></div></td>
  </tr>
<% end %>
</tbody>
</table>

app/views/zipcodes/edit.html.erb
<h3>Please Select Spots</h3>
<h3><%= @zipcode.zip %></h3>
<%= render 'form' %>

app/views/zipcodes/index.html.erb
<style type="text/css">
#search-field {
  width: 35%;
  float:left;
  margin-left:10%;
  padding: 10px;
  max-width: 180px;
}
#submit-button{
  display: inline-block;
}
#select-zip a{
  color: green;
}
body
{
  padding-left: 5px;
  float:left;
}
table{
  margin-left: 0px;
  display: inline-block;
}
</style>
<div class="row">
  <h4>Your Ads Will Be Shown to Home Owners in These ZIP Codes</h4>
</div>
<div class="row">
  <%= form_tag(zipcodes_path, :method => "get", id: "search-form") do %>
    <div id = "search-field"><%= text_field_tag :search, params[:search], placeholder: "Search Zipcodes" %></div>
    <div id = "submit-button"><%= submit_tag "Check Availability", :name => nil, :class=> "button" %></div>
  <% end %>
</div>
<div class="row">
  <%= render 'ziptable' %>
</div>
<div class="row">
  <%= link_to 'Checkout', payments_path, :color=> '#FFFFFF', :class=> "button" %>
</div>